export const constants = {
  inputTypes: {
    'textfield': {
      'cedarType': 'textfield',
      'iconClass': 'fa fa-font',
      'label': 'Text',
      'allowedInElement': true,
      'primaryField': true,
      'hasControlledTerms': true,
      'staticField': false,
      'allowsMultiple': true,
      'allowsValueRecommendation': true,
      'hasInstanceTerm': true,
      'allowsRequired': true
    },
    'controlled': {
      'cedarType': 'controlled',
      'iconClass': 'fa fa-font',
      'label': 'Controlled',
      'allowedInElement': true,
      'primaryField': true,
      'hasControlledTerms': true,
      'staticField': false,
      'allowsMultiple': true,
      'allowsValueRecommendation': true,
      'hasInstanceTerm': true,
      'allowsRequired': true
    },
    'link': {
      'cedarType': 'link',
      'iconClass': 'fa fa-font',
      'label': 'Text',
      'allowedInElement': true,
      'primaryField': true,
      'hasControlledTerms': true,
      'staticField': false,
      'allowsMultiple': true,
      'allowsValueRecommendation': true,
      'hasInstanceTerm': true,
      'allowsRequired': true
    },
    'textarea': {
      'cedarType': 'textarea',
      'iconClass': 'fa fa-paragraph',
      'label': 'Text Area',
      'allowedInElement': true,
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': false,
      'allowsMultiple': true,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': true
    },
    'radio': {
      'cedarType': 'radio',
      'iconClass': 'fa fa-dot-circle-o',
      'label': 'Multiple Choice',
      'allowedInElement': true,
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': false,
      'allowsMultiple': false,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': true
    },
    'checkbox': {
      'cedarType': 'checkbox',
      'iconClass': 'fa fa-check-square-o',
      'label': 'Checkbox',
      'allowedInElement': true,
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': false,
      'allowsMultiple': false,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': true
    },
    'date': {
      'cedarType': 'date',
      'iconClass': 'fa fa-calendar',
      'label': 'Date',
      'allowedInElement': true,
      'primaryField': true,
      'hasControlledTerms': false,
      'staticField': false,
      'allowsMultiple': true,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': true
    },
    'email': {
      'cedarType': 'email',
      'iconClass': 'fa fa-envelope',
      'label': 'Email',
      'allowedInElement': true,
      'primaryField': true,
      'hasControlledTerms': false,
      'staticField': false,
      'allowsMultiple': true,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': true
    },
    'list': {
      'cedarType': 'list',
      'iconClass': 'fa fa-list',
      'allowedInElement': true,
      'primaryField': false,
      'label': 'List',
      'hasControlledTerms': false,
      'staticField': false,
      'allowsMultiple': false,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': true
    },
    'numeric': {
      'cedarType': 'numeric',
      'iconClass': 'fa fa-hashtag',
      'allowedInElement': true,
      'primaryField': true,
      'Label': 'Number',
      'hasControlledTerms': false,
      'staticField': false,
      'allowsMultiple': true,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': true
    },
    'phone-number': {
      'cedarType': 'phone-number',
      'iconClass': 'fa fa-th',
      'allowedInElement': true,
      'label': 'Phone Number',
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': false,
      'allowsMultiple': true,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': true
    },
    'attribute-value': {
      'cedarType': 'attribute-value',
      'iconClass': 'fa fa-plus-square',
      'label': 'Attribute Value',
      'allowedInElement': true,
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': false,
      'allowsMultiple': false,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': false
    },
    'page-break': {
      'cedarType': 'page-break',
      'iconClass': 'fa fa-file-o',
      'allowedInElement': false,
      'label': 'Page Break',
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': true,
      'allowsMultiple': false,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': false
    },
    'section-break': {
      'cedarType': 'section-break',
      'iconClass': 'fa fa-minus',
      'allowedInElement': true,
      'label': 'Section Break',
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': true,
      'allowsMultiple': false,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': false
    },
    'richtext': {
      'cedarType': 'richtext',
      'iconClass': 'fa fa-pencil-square-o',
      'allowedInElement': true,
      'label': 'Rich Text',
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': true,
      'allowsMultiple': false,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': false
    },
    'image': {
      'cedarType': 'image',
      'iconClass': 'fa fa-image',
      'allowedInElement': true,
      'label': 'Image',
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': true,
      'allowsMultiple': false,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': false
    },
    'youtube': {
      'cedarType': 'youtube',
      'iconClass': 'fa fa-youtube-square',
      'allowedInElement': true,
      'label': 'YouTube Video',
      'primaryField': false,
      'hasControlledTerms': false,
      'staticField': true,
      'allowsMultiple': false,
      'allowsValueRecommendation': false,
      'hasInstanceTerm': false,
      'allowsRequired': false
    }
  },
  labels: {'copy': 'Copy', 'remove': 'Remove'}

};
