export enum InputType {
  textfield = 'textfield',
  controlled = 'controlled',
  link = 'link',
  textarea = 'textarea',
  radio = 'radio',
  checkbox = 'checkbox',
  date = 'date',
  email = 'email',
  list = 'list',
  numeric = 'numeric',
  phoneNumber = 'phone-number',
  tel = 'tel',
  text = 'text',
  url = 'url',
  number = 'number',
  attributeValue = 'attribute-value',
  pageBreak = 'page-break',
  sectionBreak = 'section-break',
  richText = 'richtext',
  image = 'image',
  youTube = 'youtube',
  static = 'static',
  element = 'element'
}

